println("Opd H02.0 console");
println();
println("Dit is een tekst.");
print("Dit is een");
print(" stukje tekst");
println(" achter elkaar geplakt!");
print("Met 2 enters.");
println();
println();
println("Opd 2.1");
println();
print("Hi,");
print(" I am Mika Roosingh.");
print(" I love playing games!");
